language: R
cache: packages
sudo: true
dist: trusty

r_build_args: --no-build-vignettes

r_check_args: --no-vignettes   # takes too long

r:
- 3.3


env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'
